use_frameworks!

platform :ios, '16.0'

target 'S11E-Pod' do
#  pod 'ScribbleForge', '0.1.35'
    pod 'ScribbleForge', :podspec => 'https://raw.githubusercontent.com/netless-io/scribbleforge-ios-release/refs/heads/main/ScribbleForge.podspec'
#     pod 'ScribbleForge', :path => '/Users/vince/agora/ScribbleForge/ScribbleForge-iOS/Scripts/ScribbleLocalFramework'
#    pod 'ScribbleForge/AgoraSpecial', '0.1.31'
#     pod 'ScribbleForge/AgoraRtmKit2.2.x', :path => '../../../scribbleforge-ios'
#    pod 'AgoraRtm_iOS', '~> 2.1.12'
    pod 'AgoraRtcEngine_iOS', '~> 4.3.0'
#    pod 'ScribbleForge', :path => '/Users/vince/agora/ScribbleForge/ScribbleForge-iOS'
    pod 'Zip'
    pod 'DebugSwift'
    pod 'SnapKit'
    pod 'Toast-Swift'
end
