use_frameworks!

platform :ios, '16.0'

target 'S11E-Pod' do
    pod 'ScribbleForge', :podspec => 'https://raw.githubusercontent.com/netless-io/scribbleforge-ios-release/refs/heads/main/ScribbleForge.podspec'
    pod 'AgoraRtcEngine_iOS', '~> 4.3.0'
    pod 'Zip'
    pod 'DebugSwift'
    pod 'SnapKit'
    pod 'Toast-Swift'
end
